### ISSUE TITLE
Nuclei executor does not accept IP addresses

### ISSUE THREAD

**Issue by lospoelos** [infobyte/faraday_agent_dispatcher#13]
In line 64 of `/usr/local/lib/python3.10/dist-packages/faraday_agent_dispatcher/static/executors/official/nuclei.py` a check is done to disallow IP addresses. Why is that? Nuclei fully support scanning IP's.
I've created a work around, after which scanning IP's works fine (Nuclei does find stuff on non-webservers):
```
if is_ip(url_parse.hostname) or is_ip(url_parse.path):
                # print(f"Is {NUCLEI_TARGET} not valid.", file=sys.stderr)
                # sys.exit()
                url = f"{NUCLEI_TARGET}"
```
OS: Kali Linux 2022.3
Faraday version: 4.1.0
faraday_agent_dispatcher: 2.4.0

**Comment by gmartinez95** [comment]
Hi @lospoelos, you are absolutely right, the next release will fix this

**Comment by lospoelos** [comment]
Thx!
