### ISSUE TITLE
"Run" button is not active in Agent section

### ISSUE THREAD

**Issue by cadet225** [infobyte/faraday_agent_dispatcher#17]
Hi Team!
![123](https://github.com/infobyte/faraday_agent_dispatcher/assets/44412207/efdd6ce1-7b21-484c-85b9-e39bd051b02c)
I can't start the agent because the "Run" button is not active. What could be the problem?
Thanks!
![faraday](https://github.com/infobyte/faraday_agent_dispatcher/assets/44412207/851a8bf1-9eda-4d3f-8ed7-b7061f9ce5ec)
![faraday-dispatcher run](https://github.com/infobyte/faraday_agent_dispatcher/assets/44412207/5f079e80-9344-41ed-9faf-6e5fbb1fc8af)
![faraday-dispatcher](https://github.com/infobyte/faraday_agent_dispatcher/assets/44412207/f10382b6-d785-4f5c-ae08-e55a0560ce4d)

**Comment by ezk06eer** [comment]
Hi this feature is resolved in latest versions. Cheers!
