### ISSUE TITLE
Fetch burp result without providing scan

### ISSUE THREAD

**Issue by Dr4s1l** [infobyte/faraday_agent_dispatcher#7]
Is there any way to use the executor to fetch already existing issue from a scan ? Don't want to provide only 1 target at a time and prefer to feed target from CLI. So I have succeeded into creating a new scan,is the dispatcher able to fetch results?
Burp plugin here

**Comment by aenima-x** [comment]
@Dr4s1l No, all the executors work in demand.
But what you can do is run the executor from faraday-cli, in that what you could make an automated process.

The other option is to make a script to fetch the data from burp, convert it to xml (this is what the executor does) and then process it with faraday-cli

**Comment by Dr4s1l** [comment]
Thanks, documentation on faraday-cli integration with agent somewhere ?

**Comment by aenima-x** [comment]
@Dr4s1l 
https://docs.faraday-cli.faradaysec.com/commands/#agents

**Comment by Dr4s1l** [comment]
Getting erro when providing multiple named scan, from what I understand they are stored in array :
```
while read url;do echo '{"NAMED_CONFIGURATION":"crawl1","NAMED_CONFIGURATION":"audit1","TARGET_URL": "'"$url"'"}' | faraday-cli agent run -a 2 -e Burp --stdin;done <delta_tango.txt
```
this look like it work but getting unknown error from logs, and looks like the 2 named config does not load, only one of them is read :
```
2021-09-05 19:42:38,553 - faraday_agent_dispatcher - INFO {MainThread} [dispatcher.py:256 - run_once()]  Parsing data: {"execution_id": 7396, "agent_id": 2, "workspace": "seed", "action": "RUN", "executor": "Burp", "args": {"NAMED_CONFIGURATION": "audit1", "TARGET_URL": "http://example.com"}}
2021-09-05 19:42:38,553 - faraday_agent_dispatcher - INFO {MainThread} [metadata_utils.py:59 - check_commands()]  Dependency check ended. Ready to go
2021-09-05 19:42:38,553 - faraday_agent_dispatcher - INFO {MainThread} [dispatcher.py:415 - run_once()]  Running Burp executor
2021-09-05 19:42:39,742 - faraday_agent_dispatcher - INFO {MainThread} [executor_helper.py:148 - end_f()]  Data sent to bulk create
2021-09-05 19:42:39,742 - faraday_agent_dispatcher - WARNING {MainThread} [dispatcher.py:471 - run_once()]  Executor Burp finished with exit code 1
```

**Comment by aenima-x** [comment]
@Dr4s1l you can do as many executions you like, faraday-dispatcher works in async mode.
each call to the burp executor receives one NAMED_CONFIGURATION and TARGET_URL

**Comment by Dr4s1l** [comment]
Would it be possible to add a parameter to add multiple named config? Plus can you provide a way to use burp without api key? I thins the error on burp executor is related to this. Have patch code to allow more threads as the executor is very slow.

**Comment by Dr4s1l** [comment]
Looks like this executor does not work, no more information could be supplied as the exit code 1 is returned by BurpSuite. Making requests by hand works far better, how to create new vulnerability using faraday-cli ?

**Comment by aenima-x** [comment]
Ok, I just realize that configurations can be a list.
I will raise this issue.
But related to the threads, you dont need it.
You can call as many executions as you want, they will run in parallel.

can you run the dispatcher in --debug to try to find the error.

**Comment by Dr4s1l** [comment]
Debug mode also available with faraday-cli ?:
```
while read url;do echo '{"NAMED_CONFIGURATION":"audit1","TARGET_URL": "'"$url"'"}' | faraday-cli agent run -a 1 -e Init --stdin;done <delta_tango.txt
```

**Comment by aenima-x** [comment]
No, in the dispatcher.
Cli is only the one who triggers it, but you have to put the dispatcher un debug
`faraday-dispatcher run --debug`

**Comment by Dr4s1l** [comment]
ok that was related to remaining occurence of BURP_KEY while patching
